<?php
define("_Phase", "Generovanie a odosielanie prístupových údajov");
define("_FirstPhase","Generovanie hesiel");
define("_File1","CSV súbor");
define("_Separator","Oddelovač");
define("_Generate","Generovať");
define("_SecondPhase","Odosielanie emailov");
define("_File2","Príloha");
define("_TitleMail","Predmet");
define("_Name","Meno");
define("_Password","Heslo");
define("_Content","Obsah emailu (záhlavia stĺpcov reprezentujú premenné v tvare '{{premenná}}')");
define("_HTML","Odoslať ako HTML");
define("_Send","Odoslať");
define("_Sender","E-mail odosielateľa");
define("_Reset","Resetuj šablónu");
define("_Warning1","Pre korektné odosielanie emailov je nutné uvádzať názov záhlavia s emailami študentov ako 'email' a menami ako 'meno'");
define("_History","História odosielanie");
define("_slovo1","Dátum odoslania");
define("_slovo2","Meno študenta");
define("_slovo3","Názov správy");